model:
  arch: "Unet"
  dim: 64
  init_dim: None
  out_dim: None
  dim_mults: [1, 2, 4, 8]
  channels: 3
  self_condition: False
  resnet_block_groups: 8
  learned_variance: False
  learned_sinusoidal_cond: False
  random_fourier_features: False
  learned_sinusoidal_dim: 16
  sinusoidal_pos_emb_theta: 10000
  attn_dim_head: 32
  attn_heads: 4
  full_attn: None
  flash_attn: False
  resnet_block_num: 2
  conditional: False
  conditional_dim: 2



vis: &vis
  channel_to_rgb: {0: "burlywood", 1: "lightblue", 2: "dimgray"}
  path: samples/one-hot/predv_128_1000_filter
  threshold: 0.7

vec:
  !!merge <<: *vis
  origin: [39.8965148476239, 116.3820984476239] # beijing
  resolution: 1 # meters per pixel
  crs: 3857 # web mercator
  channel_to_geo: {0: "Polygon", 1: "Polygon", 2: "LineString"}
  channel_to_key: {0: "building", 1: "natural", 2: "highway"}
  background: "linen" # background color for show
  dump_geojson: True



data:
  train:
    config_path: "config/data/osm_loader.yaml"

diffusion:
  timesteps: 1000
  ddim_timestep: 500
  image_size: 256
  name: DDPM
  objective: "pred_v"
  beta_schedule: "sigmoid"
  ddim_sampling_eta: 0.0
  auto_normalize: True
  offset_noise_strength: 0.0
  min_snr_gamma: 5
  min_snr_loss_weight: False

trainer:
  condition: False
  mode: "eval"
  milestone: 'latest'
  batch_size: 16
  device: cuda
  lr: 3e-4
  max_epochs: 600
  num_workers: 8
  shuffle: True
  pin_memory: True

  amp: False

  ema_decay: 0.995
  ema_update_every: 20
  adam_betas: [0.9, 0.999]
  sample_frequency: 10
  grad_accumulate: 4
  save_best_and_latest_only: False
  max_grad_norm: 1.

  split_batches: True
  mixed_precision_type: "fp16"

  num_samples: 16

  results_dir: "results/one-hot/predv_128_1000_filter"

  calculate_fid: True
  # at least 2048 samples for FID or the "nan" or "complex number" error will occur
  # 30000-50000 samples are recommended
  num_fid_samples: 2048
  inception_block_idx: 2048
