trian:
  op_train: "./config/new/outpainting_train.yaml"
  op_train_multigpu: "./config/new/outpainting_train_multigpu.yaml"
  normal_train: "./config/new/normal_train.yaml"
  inp_train: "./config/new/inpainting_train.yaml"

sample:
  op_sample: "./config/new/outpainting_sample.yaml"
  op_sample_citygen: "./config/new/outpainting_sample_citygen.yaml"
  normal_sample: "./config/new/normal_sample.yaml"
  inp_sample: "./config/new/inpainting_sample.yaml"
  inp_sample_citygen: "./config/new/inpainting_sample_citygen.yaml"
